- name: 'Install packages to allow apt'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools  
    state: latest
    update_cache: true
- name: 'Add docker GPG apt key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: 'Add docker repo'
  apt_repository: 
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: 'Update apt install latest packages'
  apt: 
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
  
- name: Start docker service
  service:
    name: docker
    state: started
  
- name: pip docker
  pip:
    executable: pip3
    name: docker